# Generated by Django 5.2.1 on 2025-05-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summoner',
            name='name',
        ),
        migrations.AddField(
            model_name='summoner',
            name='gameName',
            field=models.CharField(default='Unknown', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summoner',
            name='tagLine',
            field=models.CharField(default='_', max_length=4),
            preserve_default=False,
        ),
    ]
