# Generated by Django 5.2.1 on 2025-05-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_remove_summoner_name_summoner_gamename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='server',
            field=models.CharField(default='none', max_length=4),
            preserve_default=False,
        ),
    ]
