# Generated by Django 5.2.1 on 2025-06-01 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_summoner_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('icon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_id', models.IntegerField(unique=True)),
                ('description', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='team0_assists',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team0_deaths',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team0_kills',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team1_assists',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team1_deaths',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team1_kills',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='double_kills',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='farm',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='kill_participation',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='penta_kills',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='quadra_kills',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='team',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='triple_kills',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='wards',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='gold_per_min',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='kda',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='main_role',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='matches_num',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='minions_per_min',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='rank',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='vision_avg',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='winratio',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='game_duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='participant',
            name='assists',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='deaths',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='kills',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='win',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='tagLine',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='participant',
            name='champion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.champion'),
        ),
        migrations.AlterField(
            model_name='match',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.queue'),
        ),
        migrations.CreateModel(
            name='SummonerChampion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches_num', models.PositiveIntegerField()),
                ('winratio', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('kda', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.champion')),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.summoner')),
            ],
        ),
    ]
