# Generated by Django 5.2.1 on 2025-06-01 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_champion_queue_match_team0_assists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game_duration',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='queue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.queue'),
        ),
        migrations.AlterField(
            model_name='match',
            name='summoners',
            field=models.ManyToManyField(null=True, through='stats.Participant', to='stats.summoner'),
        ),
        migrations.AlterField(
            model_name='match',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
