# Generated by Django 5.2.1 on 2025-06-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_alter_match_game_duration_alter_match_queue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='team',
        ),
        migrations.AddField(
            model_name='participant',
            name='lane',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='team_id',
            field=models.IntegerField(null=True),
        ),
    ]
