# Generated by Django 5.2.1 on 2025-06-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_remove_participant_team_participant_lane_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='summoners',
            field=models.ManyToManyField(through='stats.Participant', to='stats.summoner'),
        ),
    ]
