# Generated by Django 5.2.1 on 2025-06-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_alter_match_summoners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='queue',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='champion',
            name='key',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='champion',
            name='icon',
            field=models.CharField(max_length=120),
        ),
        migrations.DeleteModel(
            name='Queue',
        ),
    ]
