# Generated by Django 5.2.1 on 2025-06-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_alter_match_queue_champion_key_alter_champion_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='damage_dealt',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
