# Generated by Django 5.2.1 on 2025-06-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_participant_damage_dealt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summoner',
            name='gold_per_min',
        ),
        migrations.RemoveField(
            model_name='summoner',
            name='kda',
        ),
        migrations.RemoveField(
            model_name='summoner',
            name='main_role',
        ),
        migrations.RemoveField(
            model_name='summoner',
            name='matches_num',
        ),
        migrations.RemoveField(
            model_name='summoner',
            name='minions_per_min',
        ),
        migrations.RemoveField(
            model_name='summoner',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='summoner',
            name='vision_avg',
        ),
        migrations.RemoveField(
            model_name='summoner',
            name='winratio',
        ),
        migrations.AddField(
            model_name='summoner',
            name='flex_gold_per_min',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flex_kda',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flex_loses',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flex_main_role',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flex_matches_num',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flex_minions_per_min',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flex_vision_avg',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='flex_wins',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='icon',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='rank_flex',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='rank_solo',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='solo_gold_per_min',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='solo_kda',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='solo_loses',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='solo_main_role',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='solo_matches_num',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='solo_minions_per_min',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='solo_vision_avg',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='solo_wins',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='summoner',
            name='summoner_id',
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summoner',
            name='summoner_level',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
