# Generated by Django 5.2.1 on 2025-06-01 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_remove_summoner_gold_per_min_remove_summoner_kda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summoner',
            name='flex_matches_num',
        ),
        migrations.RemoveField(
            model_name='summoner',
            name='solo_matches_num',
        ),
    ]
