# Generated by Django 5.2.1 on 2025-06-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_remove_summoner_flex_matches_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='gold_earned',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
