# Generated by Django 5.2.1 on 2025-06-01 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_participant_gold_earned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_id', models.IntegerField(unique=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='game_mode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='queue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stats.queue'),
        ),
    ]
