# Generated by Django 5.2.1 on 2025-06-01 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0013_queue_match_game_mode_alter_match_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='game_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
