# Generated by Django 5.2.1 on 2025-06-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0014_match_game_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summoner',
            name='summoner_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
